sonar.projectKey=fantasy-sports-distributed-system
sonar.projectName=Fantasy Sports Distributed System
sonar.projectVersion=1.0

# Paths to analyze
sonar.sources=backend,frontend/src,consumers,producer

# Exclusions to speed up scanning
sonar.exclusions=frontend/node_modules/**,venv/**,**/*.test.js,**/*.spec.js,**/__pycache__/**

# Specify languages
sonar.language=py,js
